language: node_js
node_js:
- 10
git:
  depth: 1
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
install:
  - npm ci;
script:
  - npm run build;
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
